{{- if .Values.certificates.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcm-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.certificates.data.cacert }}
  cacert.pem: {{ .Values.certificates.data.cacert }}
  {{- end }}
  {{- if .Values.certificates.data.cert }}
  cert.pem: {{ .Values.certificates.data.cert }}
  {{- end }}
  {{- if .Values.certificates.data.key }}
  cert.key: {{ .Values.certificates.data.key }}
  {{- end }}
{{- end }}
